name: Publish Package to npmjs.com
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build ngx-annotate-text '--configuration production'

      - name: Lint
        run: npm run lint ngx-annotate-text
        
      - name: Test
        run: npm run test-headless ngx-annotate-text
        
      - name: Publish to npmjs.com
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/ngx-annotate-text/package.json
          token: ${{ secrets.NPM_TOKEN }}
