name: Publish Package to npmjs.com

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build:lib:prod

      - name: Lint
        run: npm run lint
        
      - name: Test
        run: npm run test-headless
        
      - name: Publish to npmjs.com
        working-directory: ./dist/ngx-annotate-text
        run: npm publish
